### ISSUE TITLE
Shorthand property with calc breaks

### ISSUE THREAD

**Issue by thewilkybarkid** [Jordan-Hall/stylelint-use-logical-spec#28]
```css
inset: calc(1 * 1px);
```

is converted to

```css
inset-block: calc(1 1px);
inset-inline: *;
```

which is broken CSS, but it shouldn't be touched as it's a single value.

Meanwhile,

```css
inset: calc(1 * 1px) calc(1 * 2px);
```

should be converted to

```css
inset-block: calc(1 * 1px);
inset-inline: calc(1 * 2px);
```

but instead `TypeError: Cannot read properties of undefined (reading 'split')` is thrown.

**Comment by sc-keithbauer** [comment]
ahh, beat me to this one!

We can also add if this is used for Sass files, and people use calculations such as `padding: ($default-padding / 2);`

We can likely add a check on the string and split values while keeping `calc()` and any properties found within `()` for Sass calculations. 

Not sure how else to handle math in Sass without surrounding parenthesis

**Comment by Jordan-Hall** [comment]
I was taking a look at this, its why i struggled with with the shorthand change. I think they maybe a way but will have to spend more time looking at the AST

**Comment by WickyNilliams** [comment]
yeah same issue here. the following css trips up the rule:

```css
inset: calc(var(--n-space-s) * -1);
```

and auto-fixing results in the following:

```css
inset-block: calc(var(--n-space-s) - 1);
inset-inline: *;
```

**Comment by Jordan-Hall** [comment]
This has now been added in version 5.0.0
