### ISSUE TITLE
Don't replace shorthand values

### ISSUE THREAD

**Issue by fregante** [Jordan-Hall/stylelint-use-logical-spec#33]
This change isn't useful:

```diff
-	padding: 5px 8px;
+	padding-block: 5px;
+	padding-inline: 8px;
```

This makes it a little more readable though:

```diff
-	margin: 15px 0 10px 60px;
+	margin-block: 15px 10px;
+	margin-inline: 60px 0;
```

Logical properties make sense when they replace "left/right/top/bottom" values, but the first example especially only breaks the shorthand, it adds no value (unless you hate shorthands, but that's not the scope of the plugin)

**Comment by le0nik** [comment]
The first example wouldn't work correctly with a vertical `writing-mode`.
The second example wouldn't work correctly even with RTL.

So current behavior is ultimately correct.
