### ISSUE TITLE
Add support for css-in-js

### ISSUE THREAD

**Issue by vip30** [Jordan-Hall/stylelint-use-logical-spec#36]
I'm using emotion and would like to apply this rule in the stylelint. However, it seems it ignored the style without closure

I believe we need to ignore the expression (i.e. `${1234}`) on autofixing and support those style without closure

i.e.

```ts
import { css } from "@emotion/react";

export function setBaseContainerLayout() {
  return css`
    margin: 0 auto; // this will be ignored
    box-sizing: border-box;
    a {
       margin: 0 auto; // this will be auto fixed
    }
  `;
}
```

#35

**Comment by Jordan-Hall** [comment]
Thank you for your hard work on this. I don't css-in-js much so was unaware how this actually works.
