### ISSUE TITLE
add support to stylelint 16

### ISSUE THREAD

**Issue by ghost** [Jordan-Hall/stylelint-use-logical-spec#40]
Please support stylelint 16.0.0, the big one

Now the code is in ESM instead of CommonJS 

Very good

Stylelint team published docs to know how to migrate with ease.

No need to keep support to commons from now on.

Style lint 16 is not allowed in your package.json. remove this restriction to

**Comment by Jordan-Hall** [comment]
Thank you.  I'll make the changes later today!

**Comment by WillPresley** [comment]
Hey @Jordan-Hall, any updates on this migration? It seems that all of my other packages are good to go with Stylelint 16, except this one (which I really love using). Thanks for all the great work!

**Comment by Jordan-Hall** [comment]
Hey,

I can push up a quick fix but i started modernizing it. Our code does support ESM already whats the exact error your getting?

**Comment by WillPresley** [comment]
It seems that the plugin isn't being loaded, generally:

> ✖  Unknown rule liberty/use-logical-spec  liberty/use-logical-spec
I can try to gather some more data in a bit, if needed, have to hop on some stuff for work.

**Comment by Jordan-Hall** [comment]
Hi @WillPresley I'm not sure why it's not working still if you look at the package we support both esm and commonjs.  Looks like it's not reading esm correctly

**Comment by Jordan-Hall** [comment]
@WillPresley  thank you reached out to stylelint and there have advised how to fix there already did it based on what this fork was from (just added additonal support and correct api. I get to work on rewrite to more standard
