### ISSUE TITLE
Keep the CHANGELOG.md up-to-date

### ISSUE THREAD

**Issue by jens-duttke** [Jordan-Hall/stylelint-use-logical-spec#5]
To be able to track the changes of new releases, it would be helpful if the CHANGELOG.md would be updated.

The latest item there is still version 2.0.0 from May 12, 2018.

Thanks!

**Comment by Jordan-Hall** [comment]
Thank you! i'll update it now. I've been focusing on fixing the issues with the original project that looked abandoned

**Comment by Jordan-Hall** [comment]
Updated: https://github.com/Jordan-Hall/stylelint-use-logical-spec/blob/master/CHANGELOG.md. Thank you for noticing the error
