### ISSUE TITLE
Also transform `height` / `width` to `block-size` / `inline-size`

### ISSUE THREAD

**Issue by johan** [Jordan-Hall/stylelint-use-logical-spec#6]
This plugin is awesome!

Could it get rules for these transforms, too?

`height` → `block-size`
`min-height` → `min-block-size`
`max-height` → `max-block-size`
`width` → `inline-size`
`min-width` → `min-inline-size`
`max-width` → `max-inline-size`

**Comment by johan** [comment]
I guess the same goes for border properties: https://drafts.csswg.org/css-logical/#border-properties

**Comment by Jordan-Hall** [comment]
@johan  i'll add them in over the weekend. I'll go and check the specs out too incase I'm missing anything else.

**Comment by johan** [comment]
If you want to be super kind to [mongolian](http://mongol.ttcy.com/) folk, you might also change so the `logical` directive gets prepended to `inset` / `margin` / `padding` rules for everything but the `values.length === 1` case. 🙂

**Comment by Jordan-Hall** [comment]
@johan  Added in 3.20 which is now available sorry for the delay
