### ISSUE TITLE
Version 3.2.0 on npm, but repo has only version 3.1.0 GitHub

### ISSUE THREAD

**Issue by jens-duttke** [Jordan-Hall/stylelint-use-logical-spec#7]
The version here (3.1.0) in the repo differs from the version released on npm (3.2.0).

The CHANGELOG.md if neither here updated, nor in the bundle on npm.

What has been changed in 3.2.0? Why is the code not available here?

**Comment by Jordan-Hall** [comment]
Hi @jens-duttke 

I'm so sorry i forgot to push up the changes to git. Not updated the changelog and pushed the code. I've added support for Logical height and width as outlined in the spec

**Comment by jens-duttke** [comment]
Great, thanks!

There is just a small typo in the CHANGELOG.md now:
"3.**1**.0 (February 16th, 2021)" should be "3.**2**.0 (February 16th, 2021)"

**Comment by Jordan-Hall** [comment]
Changing now thank you for that!
